Feature/ch5616
PAIDNetwork/paid-dapp-nextjs pull request #115
Opened 2021-09-02 14:34 UTC by ryuheimat

[ch5616](https://app.clubhouse.io/masterventures/story/5616/as-a-front-end-developer-i-need-to-modify-the-dapp-main-menu-according-to-the-figma-design)

2021-09-02 15:01 UTC, 92Sam approved these changes
LGTM! Please recieve the messages

2021-09-02 15:01 UTC, 92Sam commented on redux/actions/template/saft.html.ts
> +<<<<<<< HEAD
conflict here my friend

2021-09-02 15:01 UTC, 92Sam commented on redux/actions/template/saft.html.ts
> +<<<<<<< HEAD
conflict here

2021-09-02 15:28 UTC, CoolHandLuke88 requested changes
@ryuheimat 
~~this pr looks like it was not rebased from main, unless I am missing something, 193 commits, I believe you need to rebase with your changes and then open a new PR.~~

See comments regarding merge conflict.

Thank you sir

2021-09-02 15:36 UTC, CoolHandLuke88 commented on redux/actions/template/saft.html.ts
> +=======
sam as Sams previous comment

2021-09-02 15:36 UTC, CoolHandLuke88 commented on redux/actions/template/saft.html.ts
> +=======
same as @92Sam previous comment, merge conflict.

2021-09-02 15:37 UTC, CoolHandLuke88 commented on redux/actions/template/saft.html.ts
> +=======
same as @92Sam previous comment, merge conflict.

2021-09-02 15:37 UTC, CoolHandLuke88 commented on redux/actions/template/saft.html.ts
> +>>>>>>> main
same as @92Sam previous comment, merge conflict.

2021-09-03 02:03 UTC, ryuheimat commented on redux/actions/template/saft.html.ts
> +<<<<<<< HEAD
fixed

2021-09-03 02:03 UTC, ryuheimat commented on redux/actions/template/saft.html.ts
> +<<<<<<< HEAD
fixed

2021-09-03 02:03 UTC, ryuheimat commented on redux/actions/template/saft.html.ts
> +<<<<<<< HEAD
fixed

2021-09-03 02:04 UTC, ryuheimat commented on redux/actions/template/saft.html.ts
> +=======
fixed

2021-09-03 02:04 UTC, ryuheimat commented on redux/actions/template/saft.html.ts
> +=======
fixed

2021-09-03 02:04 UTC, ryuheimat commented on redux/actions/template/saft.html.ts
> +=======
fixed

2021-09-03 02:04 UTC, ryuheimat commented on redux/actions/template/saft.html.ts
> +>>>>>>> main
fixed

2021-09-03 04:24 UTC, CoolHandLuke88 approved these changes

2021-09-03 08:38 UTC, merged