[SH1945][SH4623] - (WIP) Creation of new login flow and adapting graphql
PAIDNetwork/paid-dapp-nextjs pull request #135
Opened 2021-09-21 05:11 UTC by 92Sam

[SH4623] https://app.shortcut.com/masterventures/story/4623/as-a-backend-engineer-i-need-to-remove-xdv-from-use
[SH1945] https://app.shortcut.com/masterventures/story/1945/as-a-frontend-developer-i-need-to-integrate-magic-link-into-the-sign-up-process-in-the-dashboard

2021-09-21 18:14 UTC, CoolHandLuke88 commented on components/account-modal/LoginModal.tsx
> +        console.log("graphqlResponse ", graphqlResponse)
remove console.logs

2021-09-21 18:15 UTC, CoolHandLuke88 commented on components/account-modal/AccountModal.tsx
> +  // );
remove dead code

2021-09-21 18:15 UTC, CoolHandLuke88 commented on components/account-modal/AccountModal.tsx
>          const accountName = (`${profile.name.toLocaleLowerCase()}${profile.lastName.toLocaleLowerCase()}`).replace(/(\s)/gi, '');
remove dead code

2021-09-21 18:15 UTC, CoolHandLuke88 commented on components/account-modal/FormAccount.tsx
> +      /> */}
dead code

2021-09-21 18:15 UTC, CoolHandLuke88 commented on models/profileModel.ts
> +// import { User } from '../lib/dtos'
dead code

2021-09-21 18:15 UTC, CoolHandLuke88 commented on pages/_app.jsx
> +      //   }
dead code

2021-09-21 18:16 UTC, CoolHandLuke88 commented on pages/_app.jsx
> +        /> */}
dead code

2021-09-21 18:16 UTC, CoolHandLuke88 commented on components/account-modal/AccountModal.tsx
> +    console.log(profile, "  -- -- -- -- --", profileReducer.did)
remove console.logs

2021-09-21 18:16 UTC, CoolHandLuke88 commented on pages/_app.jsx
> +// import getDidXdv from '../utils/xdv-universal-wallet'
dead code

2021-09-21 18:17 UTC, CoolHandLuke88 commented on pages/_app.jsx
> +    // }, [passphrase])
dead code

2021-09-21 18:17 UTC, CoolHandLuke88 commented on pages/profile.tsx
> +      // setProfile(currentProfile);
dead code

2021-09-21 18:18 UTC, CoolHandLuke88 approved these changes
+1 address/ignore comments, but we should remove console.logs if not needed and dead code if no longer used.

2021-09-22 17:21 UTC, 92Sam commented
@CoolHandLuke88 could you check again, please. 

And thanks a lot.

2021-09-22 18:02 UTC, CoolHandLuke88 commented on pages/_app.jsx
>  // import PassphraseModal from '@/components/profile/PassphraseModal'
dead code

2021-09-22 18:02 UTC, CoolHandLuke88 commented on pages/profile.tsx
>        // setProfile(currentProfile);
dead code

2021-09-22 18:03 UTC, CoolHandLuke88 commented on pages/new-agreement.tsx
> +  // );
dead code

2021-09-22 18:03 UTC, CoolHandLuke88 commented on models/profileModel.ts
> +  // profileName?: string
dead code

2021-09-22 18:04 UTC, CoolHandLuke88 approved these changes
+1 address/ignore, left more comments for `dead code`

2021-09-22 18:45 UTC, zubietaroberto requested changes
Missing some changes

2021-09-22 18:45 UTC, zubietaroberto commented on components/account-modal/FormAccount.tsx
> +  user: any;
Avoid using `any`

2021-09-22 18:45 UTC, zubietaroberto commented on components/account-modal/FormLogin.tsx
> +  login: any;
Avoid using `any`

2021-09-22 18:45 UTC, zubietaroberto commented on components/account-modal/LoginModal.tsx
> +  onLogin: any;
Avoid using `any`

2021-09-22 18:45 UTC, zubietaroberto commented on models/profileModel.ts
> +  // profileName?: string
Dead code

2021-09-22 18:45 UTC, zubietaroberto commented on package.json
> +    "@magic-sdk/admin": "^1.3.0",
This library I think is only required in the server. Please verify.

2021-09-22 18:45 UTC, zubietaroberto commented on redux/actions/profile.ts
> +// export default doSetProfile
Unused line

2021-09-22 18:45 UTC, zubietaroberto commented on redux/actions/wallet.ts
> +    console.log('Wallet Values ------|', walletGraphqlValues)
Remove console.log

2021-09-22 18:45 UTC, zubietaroberto commented on redux/actions/wallet.ts
> +    console.log('User Wallet ------|', userWallet)
Remove console.log

2021-09-22 18:45 UTC, zubietaroberto commented on sass/module/pages/_index.scss
> +}
Instead of adding it here, please add this as a SCSS module, like the other components: `LoginModal.module.scss`

2021-09-23 00:33 UTC, 92Sam commented on package.json
> +    "@magic-sdk/admin": "^1.3.0",
dropped line

2021-09-23 00:35 UTC, 92Sam commented on redux/actions/wallet.ts
> +    console.log('User Wallet ------|', userWallet)
dropped

2021-09-23 03:03 UTC, 92Sam commented on sass/module/pages/_index.scss
> +}
done.

2021-09-23 03:38 UTC, bstahlhood commented
@92Sam Make sure you rebase against `main`

2021-09-23 03:46 UTC, 92Sam commented
@bstahlhood rebasing the new changes incoming.

2021-09-23 04:04 UTC, CoolHandLuke88 approved these changes

2021-09-23 13:22 UTC, zubietaroberto approved these changes
Approved changes

2021-09-23 15:31 UTC, merged