[SH9392] New Feaure adding methods mutations, inside redux for send emails from backend
PAIDNetwork/paid-dapp-nextjs pull request #143
Opened 2021-09-27 05:08 UTC by 92Sam

https://app.shortcut.com/masterventures/story/9332/as-a-front-end-developer-i-to-call-the-mutations-for-sending-emails-after-agreement-is-anchored-or-signed

2021-09-27 16:24 UTC, CoolHandLuke88 approved these changes

2021-10-04 13:35 UTC, zubietaroberto requested changes

2021-10-04 13:35 UTC, zubietaroberto commented on pages/new-agreement.tsx
> +      }))
Remove this from here. This action has to happen in the "Sign" action of the Agreement Details.

2021-10-04 14:29 UTC, 92Sam commented on pages/new-agreement.tsx
> +      }))
WIP

2021-10-04 18:18 UTC, CoolHandLuke88 approved these changes
Approved, as long as feedback is addressed.

2021-10-05 15:43 UTC, zubietaroberto requested changes

2021-10-05 15:43 UTC, zubietaroberto commented on pages/agreements.tsx
> +    }))
This goes in the AgreementDetails page, not here.

2021-10-05 16:02 UTC, CoolHandLuke88 submitted a review, later dismissed

2021-10-05 16:27 UTC, zubietaroberto approved these changes
Approved

2021-10-05 16:55 UTC, CoolHandLuke88 approved these changes

2021-10-05 16:58 UTC, merged