Feature/sc12341
PAIDNetwork/paid-dapp-nextjs pull request #228
Opened 2021-11-04 14:47 UTC by trenchcoder

2021-11-04 14:48 UTC, CoolHandLuke88 commented on sass/module/pages/_preview.scss
> +  // transform: rotate(320deg);
dead code

2021-11-04 14:49 UTC, CoolHandLuke88 submitted a review, later dismissed

2021-11-05 14:03 UTC, CoolHandLuke88 approved these changes

2021-11-05 14:06 UTC, gkmblade requested changes
Can you add a description and add [sc12341], it should get picked up by shortcut. Right now this is not linked to the story.

2021-11-05 14:21 UTC, CoolHandLuke88 approved these changes

2021-11-05 14:24 UTC, gkmblade approved these changes

2021-11-05 14:24 UTC, merged