Smart contracts integration
PAIDNetwork/paid-dapp-nextjs pull request #27
Opened 2021-06-21 16:21 UTC by mlopezdetrinidad

2021-06-21 17:17 UTC, zubietaroberto requested changes

2021-06-21 17:17 UTC, zubietaroberto commented on pages/agreements.tsx
> +            console.log('meta ==>', values);
Remove Console

2021-06-21 17:17 UTC, zubietaroberto commented on pages/new-agreement.tsx
> +      const escrowAddress = await contract.escrow();
```suggestion
      const [fee, escrowAddress] = await Promise.all([contract.fee(), contract.escrow()]);
```

2021-06-21 17:17 UTC, zubietaroberto commented on pages/profile.tsx
> +const did_jwt_1 = require('did-jwt');
Please use `import`

2021-06-21 17:17 UTC, zubietaroberto commented on pages/profile.tsx
> +            }); */
Remove comment

2021-06-21 17:17 UTC, zubietaroberto commented on pages/profile.tsx
> +      console.log(xdvWallet);
Remove Log

2021-06-21 17:17 UTC, zubietaroberto commented on pages/profile.tsx
> +      }); */
Remove Comment

2021-06-21 17:17 UTC, zubietaroberto commented on redux/actions/agreement.ts
> +// import agreementsData from '../../data/agreements';
Remove Comment

2021-06-21 17:41 UTC, rubengue submitted a review, later dismissed
great work

2021-06-21 18:58 UTC, molekilla requested changes

2021-06-21 18:58 UTC, molekilla commented on package.json
> +    "ganache": "^6.4.4",
dev deps

2021-06-21 18:58 UTC, molekilla commented on pages/agreements.tsx
> +        const myIpfsItems = (await forkedIpfsItems) || [];
we'll migrate to a gql lib later

2021-06-21 18:58 UTC, molekilla commented on pages/new-agreement.tsx
> +          contentType: '',
text/html

2021-06-22 13:56 UTC, zubietaroberto requested changes
One final change

2021-06-22 13:56 UTC, zubietaroberto commented on pages/agreements.tsx
> +                // }
Remove Comments

2021-06-22 14:15 UTC, zubietaroberto approved these changes
Approved

2021-06-22 14:18 UTC, molekilla approved these changes
lg

2021-06-22 14:31 UTC, merged